### ISSUE TITLE
Not Detect Video File ?

### ISSUE THREAD

**Issue by NoodlesStamps** [Alyetama/internetarchive-youtube#3]
Thanks for making this useful program!

When I try to use this program, the video is not detected.
It is the same situation in GithubAction. Am I using it the wrong way?

```
%env CHANNELS=3blue: https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
```

```
!ia-yt -S

--------------------------------------------------------------------------------
3blue: https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw
--------------------------------------------------------------------------------
```

```
!ia-yt 

Videos: 0it [00:00, ?it/s]
```

**Comment by NoodlesStamps** [comment]
I solved it. The cause was that I didn't make a database and collection in mongodb. I'm sorry for asking a rudimentary question.

**Comment by Alyetama** [comment]
> I solved it. The cause was that I didn't make a database and collection in mongodb. I'm sorry for asking a rudimentary question.

No problem! Glad that you solved it!
